version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myprojectdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password

  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:your_password@db/myprojectdb
    depends_on:
      - db

volumes:
  postgres_data:
